init_config:

instances:
- name: ssh
  search_string: ['ssh', 'sshd']
  thresholds:
    critical: [1, 5]
- name: anekad
  search_string: ['anekad']
  thresholds:
    critical: [1, 1]
- name: anekacli
  search_string: ['anekacli']
  thresholds:
    critical: [1, 1]
